### ISSUE TITLE
Not working on fresh install of Fedora KDE 

### ISSUE THREAD

**Issue by jaredgoodman03** [heckelson/i3-and-kde-plasma#16]
I'm running Fedora 34 on Kde 5.22.4. I followed the instructions in the README, but when I select "Plasma with i3" when logging in, it just runs Kwin. Logging into normal i3-gaps seems to work just fine. What should I try?

**Comment by MarcoAnastasio** [comment]
Same problem here, fresh install of Fedora with KDE I've created a session with i3 as WM using the session file but when i login in (selecting the correct session) it goes with KWIN.

I'm on Fedora 34 ,Qt: 5.15.2, KDE Frameworks: 5.85.0.

**Comment by pelletier** [comment]
FYI i've used this workaround on Fedora 35 successfully: https://bugzilla.redhat.com/show_bug.cgi?id=1939291#c8

**Comment by jaredgoodman03** [comment]
This made my day, thank you so much
