### ISSUE TITLE
Fix to kill existing window no longer working

### ISSUE THREAD

**Issue by wcrabtree9** [heckelson/i3-and-kde-plasma#42]
After a recent update, the "Desktop — Plasma" window that covers everything is no longer closing. xprop says:

```
WM_NAME(STRING) = "Desktop @ QRect(0,0 3840x1080) "
_NET_WM_NAME(UTF8_STRING) = "Desktop @ QRect(0,0 3840x1080)  — Plasma"
```

But neither name in my i3 config file will close the desktop window that covers the screen on log in.

**Comment by g3n35i5** [comment]
I've changed the i3 config entry from the previous suggested
```
for_window [title="Desktop — Plasma"] kill; floating enable; border none
```
to
```
for_window [title="Desktop @ QRect.*"] kill; floating enable; border none
```

and the windows disappears.

**Comment by wcrabtree9** [comment]
> ```
> for_window [title="Desktop @ QRect.*"] kill; floating enable; border none
> ```

That did it, thank you!

**Comment by g3n35i5** [comment]
> would you be willing to put in a PR for this? I imagine that more people might have the same issue

Sure, see #43 :+1:

**Comment by g3n35i5** [comment]
> That did it, thank you!

Glad it worked for you, happy to help!
