### ISSUE TITLE
Oneline command is not working

### ISSUE THREAD

**Issue by nahuelcamillo** [heckelson/i3-and-kde-plasma#47]
> Here's a oneliner on how I installed everything: $ sudo pacman -Syu && sudo pacman -S i3 feh i3-dmenu-desktop morc_menu wmctrl

I followed the steps and with the installation of packages I had a "problem" with the one-line command.
When I execute this I receive the message:
`error: target not found: i3-dmenu-desktop`

An image trying just this package:
![image](https://github.com/heckelson/i3-and-kde-plasma/assets/9520126/20004bb9-39b5-4b37-ab1f-0ea20a8da083)

I just resolved it, avoiding the installation of "i3-dmenu-desktop" and everything worked well.

**Comment by heckelson** [comment]
Hi, sorry for the late reply.

It seems that the package is now called [j3-dmenu-desktop](https://archlinux.org/packages/extra/x86_64/j4-dmenu-desktop/).

PRs are welcome if you want to make one :)
