### ISSUE TITLE
Error in config file and socket path

### ISSUE THREAD

**Issue by cervyesterday** [heckelson/i3-and-kde-plasma#5]
Hi
As the title suggests i'm having issues with config file but cannot find where is the error. when i log in to plasma-i3 session it displays the error message with the options 'show errors' and 'edit config file' but i can't choose one.
In addition when i create the config file using  `$ i3-config-wizard` it shows me the following message:
`i3: Could not connect to i3 on socket "/tmp/i3-ipc.sock": No such file or directory`
is that a problem actually? Is it linked to the config file error? (notice that the config file is created and it is in the correct folder)

Then, i've noticed that the plasma-i3.desktop file has an exclamation mark, differently from the plasma.desktop one as you can see in the screenshot 
![Screenshot_20201210_012627](https://user-images.githubusercontent.com/62951693/101705309-f081d000-3a86-11eb-8e38-33e34dc60525.png)
is that a problem too?

thanks in advance!

**Comment by ferraridamiano** [comment]
I have the same issue. Did you solve the problem?

**Comment by cervyesterday** [comment]
> I have the same issue. Did you solve the problem?

Unfortunately not. I can't remember what I did. now i switched from kubuntu to manjaro kde and had no problems with i3 configuration.
